### ISSUE TITLE
Error: Sound animation type error:  sleep length must be non-negative

### ISSUE THREAD

**Issue by dm521** [FACEGOOD/FACEGOOD-Audio2Face#49]
使用自己的思必驰Key，来跟子由美对话，出现下面截图的错误。而且还提示了 Too Many Requests。

![WX20221125-135054@2x](https://user-images.githubusercontent.com/12683955/203910097-83b46316-9a15-4dd8-999b-b999760f5ce1.png)

**Comment by dm521** [comment]
问题已经解决，关闭issue。

**Comment by ZachZou-logs** [comment]
请问是如何解决的啊，我用原代码也是这样
