### ISSUE TITLE
没有example文件夹

### ISSUE THREAD

**Issue by liuhaorandezhanghao** [FACEGOOD/FACEGOOD-Audio2Face#56]
怎么没有example文件夹了？

**Comment by SZNero** [comment]
[data_all](https://pan.baidu.com/s/1CGSzn639PUE7cUYnX4I3fQ) code : n6ty

[GoogleDrive](https://drive.google.com/drive/folders/1r7b7sfMebhtG0NSZk1yHzMaHRosb8xd1?usp=sharing)
