### ISSUE TITLE
虚拟人对话一次后报错

### ISSUE THREAD

**Issue by 1059692261** [FACEGOOD/FACEGOOD-Audio2Face#58]
错误如图所示，各位大佬有解决办法嘛？
![error](https://user-images.githubusercontent.com/44863873/211009713-2cf141ce-b785-4952-8a47-616b844e6966.png)

**Comment by 1059692261** [comment]
@SZNero @wyxogo

**Comment by wyxogo** [comment]
> 错误如图所示，各位大佬有解决办法嘛？ ![error](https://user-images.githubusercontent.com/44863873/211009713-2cf141ce-b785-4952-8a47-616b844e6966.png)

请修改`zsmeif_aispeech_config.json`
![image](https://user-images.githubusercontent.com/61509470/211127573-fab388af-0311-4e71-a540-0b456cc7b21d.png)

**Comment by 1059692261** [comment]
感谢！已解决。
