### ISSUE TITLE
主分支代码训练loss无变化

### ISSUE THREAD

**Issue by 1059692261** [FACEGOOD/FACEGOOD-Audio2Face#59]
按照教程，依次运行step1-5，发现训练时loss基本无变化，如下图：
![loss](https://user-images.githubusercontent.com/44863873/211231805-0a3e6a0a-8b94-406c-859f-8dfdb4bb3eb0.png)
最终测试虚拟人物也没有任何动作反馈。
训练数据已经改成4-16，即在step3中做了如下改动：
![dataset](https://user-images.githubusercontent.com/44863873/211231926-36968f36-5b19-4f4f-9644-32b0b3643b37.png)
不知道是不是哪里操作不正确呢，请大佬指正。@SZNero @wyxogo

**Comment by wyxogo** [comment]
首先请确保tensorflow训练无`Error`，然后查看[PR#60](https://github.com/FACEGOOD/FACEGOOD-Audio2Face/pull/60)，更新model代码

**Comment by 1059692261** [comment]
可以了，谢谢大佬回复！
