### ISSUE TITLE
请问下这个项目怎么训练呢？还有就是UE是怎么打包的呢？

### ISSUE THREAD

**Issue by huangzhengwang** [FACEGOOD/FACEGOOD-Audio2Face#69]
请问下这个项目怎么训练呢？还有就是UE是怎么打包的呢？

**Comment by SZNero** [comment]
1. please read the readme.md file first.
2. about  package the UE project ,you can this website https://docs.unrealengine.com/4.27/en-US/Basics/Projects/Packaging/
