### ISSUE TITLE
关于Step3中和116bs相关问题

### ISSUE THREAD

**Issue by 1129571** [FACEGOOD/FACEGOOD-Audio2Face#72]
![image](https://user-images.githubusercontent.com/52963740/225841660-402ecf89-cc0b-4d91-9188-82003912ece1.png)
请问这里的 var_bs_index 数组是口型先关的bs名称吗？我理解这些bs应该是要用于训练的和口型相关的bs，但是为什么我根据doc文件下的bsname.txt对应过去，有的是眉毛相关的bs，有的是眼睛相关的bs，完全对不上

**Comment by CBBKLNDT** [comment]
请问问题解决了吗  该index是基于bsname.txt的吗 我在导出模型的blendshape顺序查看时和bsname.txt不一致
