### ISSUE TITLE
How to compile LPC source code into a Linux .so file

### ISSUE THREAD

**Issue by BarryAlllen** [FACEGOOD/FACEGOOD-Audio2Face#83]
When I compile the "dllmain.cpp" file using GCC on Windows and generate the "LPC.so" file, and then try to run it on Linux, I still encounter the error: "OSError: ./lib/tensorflow/LPC.so: invalid ELF header."

**Comment by BarryAlllen** [comment]
> _No description provided._

When I compile the "dllmain.cpp" file using GCC on Windows and generate the "LPC.so" file, and then try to run it on Linux, I still encounter the error: "OSError: ./lib/tensorflow/LPC.so: invalid ELF header."

**Comment by BarryAlllen** [comment]
It's driving me crazy.

**Comment by SZNero** [comment]
just use the LPC.h LPC.cpp and lpcfunc.h file. dllmain.cpp is not need. And compile them in linux with GCC

**Comment by BarryAlllen** [comment]
> 

I tried to compile the three files you mentioned into a .so file on Linux directly, but I still encountered errors. Do I need to modify the content in the source code? I'm not very familiar with C++.

**Comment by annmusic** [comment]
> just use the LPC.h LPC.cpp and lpcfunc.h file. dllmain.cpp is not need. And compile them in linux with GCC

i am experiencing the same problem, the .h file include some header files for window, so how to modify these to work with Linux.

**Comment by SZNero** [comment]
this is a example for how to create LPC.so in  linux with cmake.
[libLPC.zip](https://github.com/FACEGOOD/FACEGOOD-Audio2Face/files/12144824/libLPC.zip)
