### ISSUE TITLE
分别在不同的机器部署示例中的UE4和Server服务，应该怎么修改UE4的IP和端口指向Server？

### ISSUE THREAD

**Issue by qiaoyafeng** [FACEGOOD/FACEGOOD-Audio2Face#89]
在zsmeif_aispeech_config.json 文件中可以设置服务端的和客户端的端口， 但是我在另一台机器上启动了示例中的FaceGoodLiveLink.exe ，应该怎么指向另一台机器上启动的Server IP和端口？

**Comment by qiaoyafeng** [comment]
@SZNero @jelowang

**Comment by nightmaring** [comment]
UE电脑固定ip，zsmeif_aispeech_config.json改ip就可以了
