### ISSUE TITLE
求问：step1里面处理数据的时候 为什么要给音频前后加上260ms的空音频呢？

### ISSUE THREAD

**Issue by anliyuan** [FACEGOOD/FACEGOOD-Audio2Face#94]
![image](https://github.com/FACEGOOD/FACEGOOD-Audio2Face/assets/20371209/593cad28-103a-44c6-8047-d3906c6629d3)

**Comment by anliyuan** [comment]
这样音频和标注要的blendshape不就错位了吗

**Comment by imtangsheng** [comment]
> 这样音频和标注要的blendshape不就错位了吗

应该每一段音频都要一段前后音频作为参考，所以在开始的时候前后各添加一段数据，用来初始化前后260ms的数据

**Comment by anliyuan** [comment]
> > 这样音频和标注要的blendshape不就错位了吗
> 
> 应该每一段音频都要一段前后音频作为参考，所以在开始的时候前后各添加一段数据，用来初始化前后260ms的数据

看明白了。谢谢大佬
